name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout el código
    - name: Checkout Code
      uses: actions/checkout@v3

    # Paso 2: Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: Construir la imagen Docker
    - name: Build Docker Image
      run: |
        docker build -t prueba_tecnica_talentob .

    # Paso 4: Ejecutar pruebas unitarias
    - name: Run Unit Tests
      run: |
        docker run --rm prueba_tecnica_talentob python -m unittest discover -s predictions -p "tests.py"

    # Paso 5: Desplegar a Railway
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        export PATH="$HOME/.railway/bin:$PATH"

    - name: Deploy to Railway
      run: |
        railway login --token $RAILWAY_TOKEN
        railway up --project=${{ secrets.RAILWAY_PROJECT_ID }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
