name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout el código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t prueba_tecnica_talentob .

      # Paso 4: Ejecutar pruebas unitarias
      - name: Run Unit Tests
        run: |
          docker run --rm prueba_tecnica_talentob python -m unittest discover -s predictions -p "tests.py"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Instalar Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

      # Paso 3: Configurar y hacer deploy
      - name: Deploy to Railway
        run: |
          railway link 415f6811-0119-4553-8514-973d2439123d
          railway up --service=7f8505a1-6486-460b-9c8e-9b9d2e246300
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
