name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout el código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t prueba_tecnica_talentob .

      # Paso 4: Ejecutar pruebas unitarias
      - name: Run Unit Tests
        run: |
          docker run --rm prueba_tecnica_talentob python -m unittest discover -s predictions -p "tests.py"

  deploy:
    # Indica que este job depende de `build`
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: my-service-id
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}
